// 工程单位数据
const companies = ref([
  {
    id: 'C001',
    name: '中国交通工程总公司',
    type: '水利施工',
    contactPerson: '赵明',
    contactPhone: '13396215124',
    address: '西安市房山区北四环6号'
  },
  {
    id: 'C002',
    name: '武汉土木工程工程局',
    type: '水利施工',
    contactPerson: '马娜',
    contactPhone: '18355769444',
    address: '广州市石景山区建国门外大街203号'
  },
  {
    id: 'C003',
    name: '天津市政工程集团公司',
    type: '建筑施工',
    contactPerson: '孙强',
    contactPhone: '17037068675',
    address: '深圳市昌平区南四环662号'
  },
  {
    id: 'C004',
    name: '上海建设工程总公司',
    type: '铁路施工',
    contactPerson: '赵伟',
    contactPhone: '17047724876',
    address: '成都市石景山区建国门外大街225号'
  },
  {
    id: 'C005',
    name: '郑州交通工程有限公司',
    type: '矿山工程',
    contactPerson: '吴丽',
    contactPhone: '17027196875',
    address: '苏州市平谷区西三环980号'
  },
  {
    id: 'C006',
    name: '成都土木工程总公司',
    type: '铁路施工',
    contactPerson: '赵鹏',
    contactPhone: '13625837307',
    address: '广州市顺义区中关村大街158号'
  },
  {
    id: 'C007',
    name: '杭州冶金工程股份有限公司',
    type: '电力工程',
    contactPerson: '周刚',
    contactPhone: '13799614195',
    address: '南京市大兴区德胜门外大街651号'
  },
  {
    id: 'C008',
    name: '天津电力工程总公司',
    type: '铁路施工',
    contactPerson: '马刚',
    contactPhone: '17212226267',
    address: '苏州市怀柔区建国门外大街127号'
  },
  {
    id: 'C009',
    name: '成都土木工程工程局',
    type: '电力工程',
    contactPerson: '赵阳',
    contactPhone: '17726011090',
    address: '广州市石景山区朝阳路16号'
  },
  {
    id: 'C010',
    name: '成都交通工程有限公司',
    type: '市政工程',
    contactPerson: '张明',
    contactPhone: '13809312656',
    address: '北京市平谷区复兴门外大街90号'
  },
  {
    id: 'C011',
    name: '杭州交通工程工程局',
    type: '公路施工',
    contactPerson: '赵刚',
    contactPhone: '13188108511',
    address: '西安市平谷区南四环754号'
  },
  {
    id: 'C012',
    name: '中国土木工程有限公司',
    type: '铁路施工',
    contactPerson: '郑辉',
    contactPhone: '13016828336',
    address: '武汉市门头沟区北四环530号'
  },
  {
    id: 'C013',
    name: '杭州建筑工程有限公司',
    type: '矿山工程',
    contactPerson: '周超',
    contactPhone: '17217705992',
    address: '武汉市丰台区建国门外大街84号'
  },
  {
    id: 'C014',
    name: '成都电力工程工程局',
    type: '冶金工程',
    contactPerson: '杨明',
    contactPhone: '17631495847',
    address: '杭州市石景山区西三环881号'
  },
  {
    id: 'C015',
    name: '西安市政工程股份有限公司',
    type: '矿山工程',
    contactPerson: '陈强',
    contactPhone: '15763511468',
    address: '南京市朝阳区王府井大街256号'
  },
  {
    id: 'C016',
    name: '重庆通信工程有限公司',
    type: '建筑施工',
    contactPerson: '郑艳',
    contactPhone: '18396886137',
    address: '武汉市石景山区建国路153号'
  },
  {
    id: 'C017',
    name: '西安冶金工程总公司',
    type: '水利施工',
    contactPerson: '吴芳',
    contactPhone: '18276276519',
    address: '苏州市大兴区复兴路765号'
  },
  {
    id: 'C018',
    name: '重庆矿山工程股份有限公司',
    type: '水利施工',
    contactPerson: '钱涛',
    contactPhone: '17303108234',
    address: '成都市昌平区西单大街169号'
  },
  {
    id: 'C019',
    name: '青岛建筑工程工程局',
    type: '通信工程',
    contactPerson: '郑强',
    contactPhone: '13225279175',
    address: '杭州市海淀区复兴路826号'
  },
  {
    id: 'C020',
    name: '西安电力工程股份有限公司',
    type: '通信工程',
    contactPerson: '孙涛',
    contactPhone: '13949175483',
    address: '成都市大兴区朝阳路751号'
  }
])

// 专家数据
const experts = ref([
  {
    id: 'E001',
    name: '赵芳专家',
    age: 39,
    gender: '女',
    specialty: '结构工程',
    researchArea: '环境影响评估、可持续发展',
    title: '高级工程师',
    company: '成都土木工程总公司',
    phone: '13559493239',
    wechat: '赵芳zhuanjia',
    workExperience: '17年从业经验，曾参与多个大型结构工程项目的设计和施工',
    reviewProjects: '参与过成都土木工程总公司等多个重点项目的评审',
    characteristics: '严谨细致，工作态度认真',
    userId: 'U001',
    参编Standards: ['GB50010-2010', 'GB50009-2012']
  },
  {
    id: 'E002',
    name: '马辉专家',
    age: 34,
    gender: '男',
    specialty: '机械工程',
    researchArea: '道路工程、桥梁设计',
    title: '教授级高工',
    company: '上海建设工程总公司',
    phone: '18314286080',
    wechat: '马辉zhuanjia',
    workExperience: '12年从业经验，曾参与多个大型机械工程项目的设计和施工',
    reviewProjects: '参与过上海建设工程总公司等多个重点项目的评审',
    characteristics: '专业知识深厚，行业经验丰富',
    userId: 'U002',
    参编Standards: ['SL378-2007', 'GB50011-2010', 'GB50034-2013']
  },
  {
    id: 'E003',
    name: '孙鹏专家',
    age: 49,
    gender: '男',
    specialty: '安全工程',
    researchArea: '城市规划、市政设施',
    title: '研究员',
    company: '西安电力工程股份有限公司',
    phone: '15917349894',
    wechat: '孙鹏zhuanjia',
    workExperience: '27年从业经验，曾参与多个大型安全工程项目的设计和施工',
    reviewProjects: '参与过西安电力工程股份有限公司等多个重点项目的评审',
    characteristics: '擅长结构安全评估，具有丰富的现场经验',
    userId: 'U003',
    参编Standards: ['GB50303-2015']
  },
  {
    id: 'E004',
    name: '刘辉专家',
    age: 56,
    gender: '男',
    specialty: '工程管理',
    researchArea: '环境影响评估、可持续发展',
    title: '高级工程师',
    company: '杭州建筑工程有限公司',
    phone: '15772230417',
    wechat: '刘辉zhuanjia',
    workExperience: '34年从业经验，曾参与多个大型工程管理项目的设计和施工',
    reviewProjects: '参与过杭州建筑工程有限公司等多个重点项目的评审',
    characteristics: '严谨细致，工作态度认真',
    userId: 'U004',
    参编Standards: ['JTG D60-2015', 'GB50204-2015', 'SL274-2001']
  },
  {
    id: 'E005',
    name: '赵磊专家',
    age: 56,
    gender: '男',
    specialty: '材料工程',
    researchArea: '通信网络、信息技术',
    title: '助理工程师',
    company: '西安市政工程股份有限公司',
    phone: '18003119958',
    wechat: '赵磊zhuanjia',
    workExperience: '34年从业经验，曾参与多个大型材料工程项目的设计和施工',
    reviewProjects: '参与过西安市政工程股份有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U005',
    参编Standards: ['JTG F80/1-2017', 'GB50011-2010', 'GB50116-2013']
  },
  {
    id: 'E006',
    name: '陈军专家',
    age: 47,
    gender: '男',
    specialty: '通信工程',
    researchArea: '城市规划、市政设施',
    title: '副教授',
    company: '西安市政工程股份有限公司',
    phone: '15741332199',
    wechat: '陈军zhuanjia',
    workExperience: '25年从业经验，曾参与多个大型通信工程项目的设计和施工',
    reviewProjects: '参与过西安市政工程股份有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U006',
    参编Standards: ['GB50010-2010']
  },
  {
    id: 'E007',
    name: '杨勇专家',
    age: 32,
    gender: '男',
    specialty: '机械工程',
    researchArea: '工程造价、成本控制',
    title: '工程师',
    company: '重庆矿山工程股份有限公司',
    phone: '17722610112',
    wechat: '杨勇zhuanjia',
    workExperience: '10年从业经验，曾参与多个大型机械工程项目的设计和施工',
    reviewProjects: '参与过重庆矿山工程股份有限公司等多个重点项目的评审',
    characteristics: '专业知识深厚，行业经验丰富',
    userId: 'U007',
    参编Standards: ['JTG D60-2015', 'GB50011-2010']
  },
  {
    id: 'E008',
    name: '郑健专家',
    age: 54,
    gender: '男',
    specialty: '材料工程',
    researchArea: '工程管理、项目策划',
    title: '教授级高工',
    company: '西安市政工程股份有限公司',
    phone: '15695416120',
    wechat: '郑健zhuanjia',
    workExperience: '32年从业经验，曾参与多个大型材料工程项目的设计和施工',
    reviewProjects: '参与过西安市政工程股份有限公司等多个重点项目的评审',
    characteristics: '理论基础扎实，具有全局视野',
    userId: 'U008',
    参编Standards: ['GB50166-2017']
  },
  {
    id: 'E009',
    name: '赵明专家',
    age: 54,
    gender: '男',
    specialty: '工程管理',
    researchArea: '建筑节能、绿色建筑',
    title: '副教授',
    company: '成都电力工程工程局',
    phone: '17187877482',
    wechat: '赵明zhuanjia',
    workExperience: '32年从业经验，曾参与多个大型工程管理项目的设计和施工',
    reviewProjects: '参与过成都电力工程工程局等多个重点项目的评审',
    characteristics: '专业知识深厚，行业经验丰富',
    userId: 'U009',
    参编Standards: ['SL274-2001']
  },
  {
    id: 'E010',
    name: '郑明专家',
    age: 50,
    gender: '女',
    specialty: '结构工程',
    researchArea: '城市规划、市政设施',
    title: '教授',
    company: '上海建设工程总公司',
    phone: '18426674359',
    wechat: '郑明zhuanjia',
    workExperience: '28年从业经验，曾参与多个大型结构工程项目的设计和施工',
    reviewProjects: '参与过上海建设工程总公司等多个重点项目的评审',
    characteristics: '擅长结构安全评估，具有丰富的现场经验',
    userId: 'U010',
    参编Standards: ['GB50204-2015', 'GB50166-2017']
  },
  {
    id: 'E011',
    name: '陈军专家',
    age: 56,
    gender: '男',
    specialty: '工程监理',
    researchArea: '工程造价、成本控制',
    title: '助理工程师',
    company: '中国土木工程有限公司',
    phone: '17636736843',
    wechat: '陈军zhuanjia',
    workExperience: '34年从业经验，曾参与多个大型工程监理项目的设计和施工',
    reviewProjects: '参与过中国土木工程有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U011',
    参编Standards: ['GB50204-2015', 'GB50011-2010']
  },
  {
    id: 'E012',
    name: '赵丽专家',
    age: 44,
    gender: '女',
    specialty: '安全工程',
    researchArea: '机械设计、设备管理',
    title: '助理工程师',
    company: '中国土木工程有限公司',
    phone: '13906333618',
    wechat: '赵丽zhuanjia',
    workExperience: '22年从业经验，曾参与多个大型安全工程项目的设计和施工',
    reviewProjects: '参与过中国土木工程有限公司等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U012',
    参编Standards: ['SL378-2007', 'GB50010-2010']
  },
  {
    id: 'E013',
    name: '吴静专家',
    age: 32,
    gender: '女',
    specialty: '电气工程',
    researchArea: '工程监理、质量控制',
    title: '副研究员',
    company: '武汉土木工程工程局',
    phone: '18846796525',
    wechat: '吴静zhuanjia',
    workExperience: '10年从业经验，曾参与多个大型电气工程项目的设计和施工',
    reviewProjects: '参与过武汉土木工程工程局等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U013',
    参编Standards: ['JTG F80/1-2017']
  },
  {
    id: 'E014',
    name: '王军专家',
    age: 59,
    gender: '男',
    specialty: '交通工程',
    researchArea: '工程造价、成本控制',
    title: '助理工程师',
    company: '重庆矿山工程股份有限公司',
    phone: '17160143869',
    wechat: '王军zhuanjia',
    workExperience: '37年从业经验，曾参与多个大型交通工程项目的设计和施工',
    reviewProjects: '参与过重庆矿山工程股份有限公司等多个重点项目的评审',
    characteristics: '沟通能力强，团队协作精神好',
    userId: 'U014',
    参编Standards: ['SL274-2001']
  },
  {
    id: 'E015',
    name: '刘伟专家',
    age: 58,
    gender: '男',
    specialty: '水利工程',
    researchArea: '预应力结构、抗震设计',
    title: '高级工程师',
    company: '中国土木工程有限公司',
    phone: '18757781163',
    wechat: '刘伟zhuanjia',
    workExperience: '36年从业经验，曾参与多个大型水利工程项目的设计和施工',
    reviewProjects: '参与过中国土木工程有限公司等多个重点项目的评审',
    characteristics: '专业知识深厚，行业经验丰富',
    userId: 'U015',
    参编Standards: ['GB50166-2017', 'GB50010-2010', 'GB50011-2010']
  },
  {
    id: 'E016',
    name: '周鹏专家',
    age: 43,
    gender: '男',
    specialty: '电气工程',
    researchArea: '安全管理、风险评估',
    title: '副教授',
    company: '郑州交通工程有限公司',
    phone: '18053138675',
    wechat: '周鹏zhuanjia',
    workExperience: '21年从业经验，曾参与多个大型电气工程项目的设计和施工',
    reviewProjects: '参与过郑州交通工程有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U016',
    参编Standards: ['GB50010-2010']
  },
  {
    id: 'E017',
    name: '陈鹏专家',
    age: 34,
    gender: '男',
    specialty: '建筑设计',
    researchArea: '安全管理、风险评估',
    title: '高级工程师',
    company: '重庆矿山工程股份有限公司',
    phone: '18695053475',
    wechat: '陈鹏zhuanjia',
    workExperience: '12年从业经验，曾参与多个大型建筑设计项目的设计和施工',
    reviewProjects: '参与过重庆矿山工程股份有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U017',
    参编Standards: ['GB50009-2012', 'SL378-2007']
  },
  {
    id: 'E018',
    name: '张杰专家',
    age: 34,
    gender: '男',
    specialty: '电气工程',
    researchArea: '机械设计、设备管理',
    title: '副教授',
    company: '重庆通信工程有限公司',
    phone: '18906859624',
    wechat: '张杰zhuanjia',
    workExperience: '12年从业经验，曾参与多个大型电气工程项目的设计和施工',
    reviewProjects: '参与过重庆通信工程有限公司等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U018',
    参编Standards: ['GB50010-2010', 'GB50303-2015']
  },
  {
    id: 'E019',
    name: '王伟专家',
    age: 34,
    gender: '男',
    specialty: '机械工程',
    researchArea: '安全管理、风险评估',
    title: '助理工程师',
    company: '重庆通信工程有限公司',
    phone: '15334881969',
    wechat: '王伟zhuanjia',
    workExperience: '12年从业经验，曾参与多个大型机械工程项目的设计和施工',
    reviewProjects: '参与过重庆通信工程有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U019',
    参编Standards: ['SL274-2001', 'JTG F80/1-2017']
  },
  {
    id: 'E020',
    name: '刘强专家',
    age: 58,
    gender: '男',
    specialty: '通信工程',
    researchArea: '工程管理、项目策划',
    title: '助理工程师',
    company: '天津电力工程总公司',
    phone: '17279466054',
    wechat: '刘强zhuanjia',
    workExperience: '36年从业经验，曾参与多个大型通信工程项目的设计和施工',
    reviewProjects: '参与过天津电力工程总公司等多个重点项目的评审',
    characteristics: '沟通能力强，团队协作精神好',
    userId: 'U020',
    参编Standards: ['JTG D60-2015']
  },
  {
    id: 'E021',
    name: '杨超专家',
    age: 48,
    gender: '男',
    specialty: '工程管理',
    researchArea: '工程管理、项目策划',
    title: '高级工程师',
    company: '郑州交通工程有限公司',
    phone: '13817288983',
    wechat: '杨超zhuanjia',
    workExperience: '26年从业经验，曾参与多个大型工程管理项目的设计和施工',
    reviewProjects: '参与过郑州交通工程有限公司等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U021',
    参编Standards: ['GB50010-2010', 'GB50034-2013']
  },
  {
    id: 'E022',
    name: '刘勇专家',
    age: 39,
    gender: '男',
    specialty: '市政工程',
    researchArea: '结构力学、施工技术',
    title: '教授级高工',
    company: '武汉土木工程工程局',
    phone: '17048980037',
    wechat: '刘勇zhuanjia',
    workExperience: '17年从业经验，曾参与多个大型市政工程项目的设计和施工',
    reviewProjects: '参与过武汉土木工程工程局等多个重点项目的评审',
    characteristics: '注重细节，擅长复杂结构分析',
    userId: 'U022',
    参编Standards: ['SL274-2001', 'SL378-2007', 'GB50034-2013']
  },
  {
    id: 'E023',
    name: '赵辉专家',
    age: 33,
    gender: '男',
    specialty: '工程造价',
    researchArea: '水力学、水利枢纽设计',
    title: '助理工程师',
    company: '中国交通工程总公司',
    phone: '15961697454',
    wechat: '赵辉zhuanjia',
    workExperience: '11年从业经验，曾参与多个大型工程造价项目的设计和施工',
    reviewProjects: '参与过中国交通工程总公司等多个重点项目的评审',
    characteristics: '沟通能力强，团队协作精神好',
    userId: 'U023',
    参编Standards: ['GB50166-2017', 'JTG D60-2015']
  },
  {
    id: 'E024',
    name: '吴静专家',
    age: 43,
    gender: '女',
    specialty: '工程管理',
    researchArea: '机械设计、设备管理',
    title: '研究员',
    company: '西安市政工程股份有限公司',
    phone: '15246179030',
    wechat: '吴静zhuanjia',
    workExperience: '21年从业经验，曾参与多个大型工程管理项目的设计和施工',
    reviewProjects: '参与过西安市政工程股份有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U024',
    参编Standards: ['GB50166-2017', 'GB50303-2015']
  },
  {
    id: 'E025',
    name: '赵刚专家',
    age: 37,
    gender: '男',
    specialty: '结构工程',
    researchArea: '工程管理、项目策划',
    title: '工程师',
    company: '重庆矿山工程股份有限公司',
    phone: '13735112589',
    wechat: '赵刚zhuanjia',
    workExperience: '15年从业经验，曾参与多个大型结构工程项目的设计和施工',
    reviewProjects: '参与过重庆矿山工程股份有限公司等多个重点项目的评审',
    characteristics: '理论基础扎实，具有全局视野',
    userId: 'U025',
    参编Standards: ['GB50010-2010']
  },
  {
    id: 'E026',
    name: '钱涛专家',
    age: 52,
    gender: '女',
    specialty: '安全工程',
    researchArea: '电力系统、新能源',
    title: '副研究员',
    company: '青岛建筑工程工程局',
    phone: '17050205626',
    wechat: '钱涛zhuanjia',
    workExperience: '30年从业经验，曾参与多个大型安全工程项目的设计和施工',
    reviewProjects: '参与过青岛建筑工程工程局等多个重点项目的评审',
    characteristics: '理论基础扎实，具有全局视野',
    userId: 'U026',
    参编Standards: ['GB50011-2010']
  },
  {
    id: 'E027',
    name: '陈阳专家',
    age: 44,
    gender: '女',
    specialty: '结构工程',
    researchArea: '通信网络、信息技术',
    title: '助理工程师',
    company: '杭州建筑工程有限公司',
    phone: '18292313520',
    wechat: '陈阳zhuanjia',
    workExperience: '22年从业经验，曾参与多个大型结构工程项目的设计和施工',
    reviewProjects: '参与过杭州建筑工程有限公司等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U027',
    参编Standards: ['GB50116-2013', 'SL378-2007']
  },
  {
    id: 'E028',
    name: '李明专家',
    age: 35,
    gender: '男',
    specialty: '工程监理',
    researchArea: '工程造价、成本控制',
    title: '工程师',
    company: '上海建设工程总公司',
    phone: '13986259622',
    wechat: '李明zhuanjia',
    workExperience: '13年从业经验，曾参与多个大型工程监理项目的设计和施工',
    reviewProjects: '参与过上海建设工程总公司等多个重点项目的评审',
    characteristics: '注重细节，擅长复杂结构分析',
    userId: 'U028',
    参编Standards: ['JTG D60-2015', 'GB50011-2010']
  },
  {
    id: 'E029',
    name: '黄静专家',
    age: 42,
    gender: '女',
    specialty: '结构工程',
    researchArea: '环境影响评估、可持续发展',
    title: '高级工程师',
    company: '天津电力工程总公司',
    phone: '15119485870',
    wechat: '黄静zhuanjia',
    workExperience: '20年从业经验，曾参与多个大型结构工程项目的设计和施工',
    reviewProjects: '参与过天津电力工程总公司等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U029',
    参编Standards: ['SL274-2001', 'GB50034-2013', 'GB50010-2010']
  },
  {
    id: 'E030',
    name: '孙辉专家',
    age: 32,
    gender: '男',
    specialty: '工程管理',
    researchArea: '工程造价、成本控制',
    title: '工程师',
    company: '中国交通工程总公司',
    phone: '17837309686',
    wechat: '孙辉zhuanjia',
    workExperience: '10年从业经验，曾参与多个大型工程管理项目的设计和施工',
    reviewProjects: '参与过中国交通工程总公司等多个重点项目的评审',
    characteristics: '严谨细致，工作态度认真',
    userId: 'U030',
    参编Standards: ['GB50034-2013']
  },
  {
    id: 'E031',
    name: '孙涛专家',
    age: 47,
    gender: '男',
    specialty: '建筑设计',
    researchArea: '环境影响评估、可持续发展',
    title: '教授',
    company: '成都交通工程有限公司',
    phone: '18437714314',
    wechat: '孙涛zhuanjia',
    workExperience: '25年从业经验，曾参与多个大型建筑设计项目的设计和施工',
    reviewProjects: '参与过成都交通工程有限公司等多个重点项目的评审',
    characteristics: '沟通能力强，团队协作精神好',
    userId: 'U031',
    参编Standards: ['GB50009-2012', 'JTG F80/1-2017', 'GB50034-2013']
  },
  {
    id: 'E032',
    name: '赵勇专家',
    age: 48,
    gender: '男',
    specialty: '市政工程',
    researchArea: '工程监理、质量控制',
    title: '研究员',
    company: '杭州建筑工程有限公司',
    phone: '15269189974',
    wechat: '赵勇zhuanjia',
    workExperience: '26年从业经验，曾参与多个大型市政工程项目的设计和施工',
    reviewProjects: '参与过杭州建筑工程有限公司等多个重点项目的评审',
    characteristics: '理论基础扎实，具有全局视野',
    userId: 'U032',
    参编Standards: ['GB50010-2010']
  },
  {
    id: 'E033',
    name: '钱军专家',
    age: 43,
    gender: '男',
    specialty: '通信工程',
    researchArea: '结构力学、施工技术',
    title: '助理工程师',
    company: '天津市政工程集团公司',
    phone: '13186681520',
    wechat: '钱军zhuanjia',
    workExperience: '21年从业经验，曾参与多个大型通信工程项目的设计和施工',
    reviewProjects: '参与过天津市政工程集团公司等多个重点项目的评审',
    characteristics: '理论基础扎实，具有全局视野',
    userId: 'U033',
    参编Standards: ['GB50303-2015', 'GB50011-2010']
  },
  {
    id: 'E034',
    name: '孙军专家',
    age: 41,
    gender: '男',
    specialty: '机械工程',
    researchArea: '城市规划、市政设施',
    title: '教授级高工',
    company: '成都交通工程有限公司',
    phone: '15339433038',
    wechat: '孙军zhuanjia',
    workExperience: '19年从业经验，曾参与多个大型机械工程项目的设计和施工',
    reviewProjects: '参与过成都交通工程有限公司等多个重点项目的评审',
    characteristics: '严谨细致，工作态度认真',
    userId: 'U034',
    参编Standards: ['GB50303-2015', 'SL274-2001', 'GB50011-2010']
  },
  {
    id: 'E035',
    name: '李刚专家',
    age: 58,
    gender: '男',
    specialty: '工程管理',
    researchArea: '水力学、水利枢纽设计',
    title: '工程师',
    company: '郑州交通工程有限公司',
    phone: '17746287358',
    wechat: '李刚zhuanjia',
    workExperience: '36年从业经验，曾参与多个大型工程管理项目的设计和施工',
    reviewProjects: '参与过郑州交通工程有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U035',
    参编Standards: ['GB50116-2013']
  },
  {
    id: 'E036',
    name: '李艳专家',
    age: 32,
    gender: '女',
    specialty: '工程造价',
    researchArea: '环境影响评估、可持续发展',
    title: '工程师',
    company: '杭州建筑工程有限公司',
    phone: '13976502474',
    wechat: '李艳zhuanjia',
    workExperience: '10年从业经验，曾参与多个大型工程造价项目的设计和施工',
    reviewProjects: '参与过杭州建筑工程有限公司等多个重点项目的评审',
    characteristics: '严谨细致，工作态度认真',
    userId: 'U036',
    参编Standards: ['GB50011-2010']
  },
  {
    id: 'E037',
    name: '钱健专家',
    age: 58,
    gender: '女',
    specialty: '工程监理',
    researchArea: '机械设计、设备管理',
    title: '教授级高工',
    company: '成都交通工程有限公司',
    phone: '18494229170',
    wechat: '钱健zhuanjia',
    workExperience: '36年从业经验，曾参与多个大型工程监理项目的设计和施工',
    reviewProjects: '参与过成都交通工程有限公司等多个重点项目的评审',
    characteristics: '擅长结构安全评估，具有丰富的现场经验',
    userId: 'U037',
    参编Standards: ['SL274-2001', 'JTG F80/1-2017']
  },
  {
    id: 'E038',
    name: '吴杰专家',
    age: 32,
    gender: '男',
    specialty: '安全工程',
    researchArea: '工程管理、项目策划',
    title: '助理工程师',
    company: '重庆矿山工程股份有限公司',
    phone: '18759247535',
    wechat: '吴杰zhuanjia',
    workExperience: '10年从业经验，曾参与多个大型安全工程项目的设计和施工',
    reviewProjects: '参与过重庆矿山工程股份有限公司等多个重点项目的评审',
    characteristics: '注重细节，擅长复杂结构分析',
    userId: 'U038',
    参编Standards: ['GB50204-2015', 'JTG D60-2015', 'GB50303-2015']
  },
  {
    id: 'E039',
    name: '赵杰专家',
    age: 38,
    gender: '男',
    specialty: '机械工程',
    researchArea: '环境影响评估、可持续发展',
    title: '教授',
    company: '中国交通工程总公司',
    phone: '15611563627',
    wechat: '赵杰zhuanjia',
    workExperience: '16年从业经验，曾参与多个大型机械工程项目的设计和施工',
    reviewProjects: '参与过中国交通工程总公司等多个重点项目的评审',
    characteristics: '沟通能力强，团队协作精神好',
    userId: 'U039',
    参编Standards: ['GB50009-2012', 'GB50011-2010']
  },
  {
    id: 'E040',
    name: '钱涛专家',
    age: 44,
    gender: '男',
    specialty: '通信工程',
    researchArea: '工程管理、项目策划',
    title: '副教授',
    company: '上海建设工程总公司',
    phone: '18837395045',
    wechat: '钱涛zhuanjia',
    workExperience: '22年从业经验，曾参与多个大型通信工程项目的设计和施工',
    reviewProjects: '参与过上海建设工程总公司等多个重点项目的评审',
    characteristics: '专业知识深厚，行业经验丰富',
    userId: 'U040',
    参编Standards: ['JTG D60-2015', 'SL378-2007']
  },
  {
    id: 'E041',
    name: '张军专家',
    age: 54,
    gender: '男',
    specialty: '结构工程',
    researchArea: '工程监理、质量控制',
    title: '高级工程师',
    company: '中国土木工程有限公司',
    phone: '17159541611',
    wechat: '张军zhuanjia',
    workExperience: '32年从业经验，曾参与多个大型结构工程项目的设计和施工',
    reviewProjects: '参与过中国土木工程有限公司等多个重点项目的评审',
    characteristics: '严谨细致，工作态度认真',
    userId: 'U041',
    参编Standards: ['GB50204-2015']
  },
  {
    id: 'E042',
    name: '黄勇专家',
    age: 55,
    gender: '男',
    specialty: '市政工程',
    researchArea: '环境影响评估、可持续发展',
    title: '副研究员',
    company: '青岛建筑工程工程局',
    phone: '18418523940',
    wechat: '黄勇zhuanjia',
    workExperience: '33年从业经验，曾参与多个大型市政工程项目的设计和施工',
    reviewProjects: '参与过青岛建筑工程工程局等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U042',
    参编Standards: ['GB50011-2010']
  },
  {
    id: 'E043',
    name: '杨刚专家',
    age: 36,
    gender: '男',
    specialty: '工程管理',
    researchArea: '工程管理、项目策划',
    title: '助理工程师',
    company: '成都土木工程工程局',
    phone: '17242228723',
    wechat: '杨刚zhuanjia',
    workExperience: '14年从业经验，曾参与多个大型工程管理项目的设计和施工',
    reviewProjects: '参与过成都土木工程工程局等多个重点项目的评审',
    characteristics: '擅长结构安全评估，具有丰富的现场经验',
    userId: 'U043',
    参编Standards: ['GB50303-2015', 'GB50034-2013', 'GB50166-2017']
  },
  {
    id: 'E044',
    name: '赵辉专家',
    age: 57,
    gender: '男',
    specialty: '环境工程',
    researchArea: '工程监理、质量控制',
    title: '教授',
    company: '郑州交通工程有限公司',
    phone: '18612889431',
    wechat: '赵辉zhuanjia',
    workExperience: '35年从业经验，曾参与多个大型环境工程项目的设计和施工',
    reviewProjects: '参与过郑州交通工程有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U044',
    参编Standards: ['GB50010-2010']
  },
  {
    id: 'E045',
    name: '赵刚专家',
    age: 30,
    gender: '女',
    specialty: '水利工程',
    researchArea: '工程管理、项目策划',
    title: '高级工程师',
    company: '中国交通工程总公司',
    phone: '13782529377',
    wechat: '赵刚zhuanjia',
    workExperience: '8年从业经验，曾参与多个大型水利工程项目的设计和施工',
    reviewProjects: '参与过中国交通工程总公司等多个重点项目的评审',
    characteristics: '沟通能力强，团队协作精神好',
    userId: 'U045',
    参编Standards: ['GB50116-2013', 'JTG D60-2015', 'GB50009-2012']
  },
  {
    id: 'E046',
    name: '郑涛专家',
    age: 57,
    gender: '男',
    specialty: '水利工程',
    researchArea: '城市规划、市政设施',
    title: '教授',
    company: '成都土木工程工程局',
    phone: '17822820847',
    wechat: '郑涛zhuanjia',
    workExperience: '35年从业经验，曾参与多个大型水利工程项目的设计和施工',
    reviewProjects: '参与过成都土木工程工程局等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U046',
    参编Standards: ['GB50166-2017']
  },
  {
    id: 'E047',
    name: '郑阳专家',
    age: 37,
    gender: '男',
    specialty: '结构工程',
    researchArea: '城市规划、市政设施',
    title: '工程师',
    company: '郑州交通工程有限公司',
    phone: '15389815594',
    wechat: '郑阳zhuanjia',
    workExperience: '15年从业经验，曾参与多个大型结构工程项目的设计和施工',
    reviewProjects: '参与过郑州交通工程有限公司等多个重点项目的评审',
    characteristics: '技术全面，实践经验丰富',
    userId: 'U047',
    参编Standards: ['GB50116-2013', 'GB50204-2015', 'JTG F80/1-2017']
  },
  {
    id: 'E048',
    name: '刘军专家',
    age: 37,
    gender: '男',
    specialty: '土木工程',
    researchArea: '机械设计、设备管理',
    title: '教授级高工',
    company: '重庆矿山工程股份有限公司',
    phone: '18563167717',
    wechat: '刘军zhuanjia',
    workExperience: '15年从业经验，曾参与多个大型土木工程项目的设计和施工',
    reviewProjects: '参与过重庆矿山工程股份有限公司等多个重点项目的评审',
    characteristics: '理论基础扎实，具有全局视野',
    userId: 'U048',
    参编Standards: ['GB50204-2015']
  },
  {
    id: 'E049',
    name: '郑伟专家',
    age: 55,
    gender: '男',
    specialty: '工程监理',
    researchArea: '工程监理、质量控制',
    title: '教授级高工',
    company: '西安市政工程股份有限公司',
    phone: '13090215689',
    wechat: '郑伟zhuanjia',
    workExperience: '33年从业经验，曾参与多个大型工程监理项目的设计和施工',
    reviewProjects: '参与过西安市政工程股份有限公司等多个重点项目的评审',
    characteristics: '创新能力强，善于解决复杂问题',
    userId: 'U049',
    参编Standards: ['GB50034-2013', 'SL378-2007']
  },
  {
    id: 'E050',
    name: '郑涛专家',
    age: 44,
    gender: '女',
    specialty: '材料工程',
    researchArea: '安全管理、风险评估',
    title: '教授',
    company: '杭州冶金工程股份有限公司',
    phone: '18822819793',
    wechat: '郑涛zhuanjia',
    workExperience: '22年从业经验，曾参与多个大型材料工程项目的设计和施工',
    reviewProjects: '参与过杭州冶金工程股份有限公司等多个重点项目的评审',
    characteristics: '沟通能力强，团队协作精神好',
    userId: 'U050',
    参编Standards: ['GB50166-2017']
  }
])