locations=filesystem:flyway/sql/mysql
connectRetries=10
baselineOnMigrate=true
validateMigrationNaming=true
sqlMigrationSuffixes=.sql
url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
user=${MYSQL_USER}
password=${MYSQL_PASSWORD}
