locations=filesystem:flyway/sql/postgres
connectRetries=10
baselineOnMigrate=true
validateMigrationNaming=true
sqlMigrationSuffixes=.sql
url=jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
user=${PG_USER}
password=${PG_PASSWORD}
